version: '3.9'

services:
  backend:
    container_name: java_backend
    image: java-app:1.0.0
    build: .
    env_file:
      - .env
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DB_PORT=${DB_PORT}
      - DB_URI=${DB_URI}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${SERVER_PORT}:8080

  postgresql:
    image: postgres:17
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    environment:
      - DB_PORT= ${DB_PORT}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}